name: Daily_Scan

on:
  push:
    branches:
    - release/*
    - master
  schedule:
  - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run gitleaks scan
      run: |
        sh detect.sh
